### ISSUE TITLE
Strange bug adding components

### ISSUE THREAD

**Issue by rosshadden** [lovetoys/lovetoys#60] opened 2016-09-05 05:17 UTC
It has taken me several days to get this down to a minimal example, because for the longest time I thought it was just something in my own code.  I have not figured out exactly what in lovetoys is causing this issue, but I was able to verify that it is a problem in lovetoys itself.  Also I don't really think lovetoys is actually even usable in this state, so I don't know if people are just using old versions or using the same components on every entity to get around it or what.

I am going to explain through example.  I cloned the [example repo](https://github.com/lovetoys/example) (to make sure it wasn't an issue in my own codebase), and made the following changes:

I added these functions to `TestSystem`:

``` lua
function TestSystem:update()
    print(#self.targets)
    love.event.quit()
end

function TestSystem:requires()
    return { 'Position' }
end
```

And I changed the last block of code in the `love.load` function in `main.lua` to this:

``` lua
    local foo = Entity()
    -- foo:add(Position(100, 100))
    engine:addEntity(foo)

    local bar = Entity()
    bar:add(Position(100, 100))
    engine:addEntity(bar)

    -- -- Creation and adding of some Entities
    -- for i = 1, 20, 1 do
    --     entity = Entity()
    --     local x, y = love.math.random(100, 900), love.math.random(150, 600)
    --     entity:add(DrawablePolygon(world, x, y, 100, 10, "static", wall))
    --     entity:add(Timing(love.math.random(0, 5000)))
    --     -- entity:add(Position(x, y))
    --     entity:get("DrawablePolygon").fixture:setUserData(entity)
    --     engine:addEntity(entity)
    -- end
```

The expected result is that the `TestSystem` would print `1`, as one entity (`bar`) exists with `Postion`.  But the act of adding an entity before it, `foo`, makes it instead print `2`.  Even though `foo` does _not_ have the `Position` component.

The order here is very important (and why it took me so long to learn about the bug).  If I flip them, and add `Position` to `foo` instead of `bar`, I get `1` printed as expected.

``` lua
    local foo = Entity()
    foo:add(Position(100, 100))
    engine:addEntity(foo)

    local bar = Entity()
    -- bar:add(Position(100, 100))
    engine:addEntity(bar)
```

**Comment by rosshadden** [comment] 2016-09-05 05:22
Note that `Position` has nothing to do with it.  This is true for any component, any system, and any entities.  My own codebase has REALLY crazy problems stemming from this, as the problem gets a lot worse with more entities and more components.  It seems like the entities that are defined later are adding their components to the ones that were defined earlier.

**Comment by rosshadden** [comment] 2016-09-05 05:33
Also looping through the entities in the targets table of the system reveals that the duplicate targets are all `nil`.  So in the first example, the `foo` entry is `nil`, and `bar` is the expected entity.

**Comment by raffomania** [comment] 2016-09-29 11:24
Sorry we're being so slow. I'm now looking into it.

**Comment by mpicard** [comment] 2016-10-12 15:44
What version of Lua are you using @rosshadden ? Similarly, what version of Lua is lovetoys developed for @raffomania ? (Out of curiosity mostly)

There seems to be a "bug" in the table length operator `#` that counts elements that are nil I believe. It seems as though the TestSystem.targets for some reason is picking up then nulling `foo`? The work around I use is to do pairs(self.targets) to filter out the nils:
```lua
function TestSystem:update(dt)
    local count = 0
    for k,v in pairs(self.targets) do count = count + 1 end
    print(("#self.targets = %d, count = %d"):format(#self.targets, count))
    love.event.quit()
end
```
Have you made any progress @raffomania ? I'd like to help so if you have any ideas let me know.

**Comment by rosshadden** [comment] 2016-10-12 17:30
@mpicard I am using love2d, in which the latest version uses luajit 2.0.4.

In my own ECS, [SECS](https://github.com/acleverpun/secs), I store entities in arrays (numerically-indexed tables) on systems, rather than tables with keys.  It is faster to enumerate numeric tables ([ref 1](https://www.lua.org/gems/sample.pdf), [ref 2](http://lua-users.org/wiki/OptimisationCodingTips)), and they do not suffer from this problem.

**Comment by raffomania** [comment] 2016-10-13 10:02
@mpicard we develop against the version love2d is using, which is luajit 2.0.4 as @rosshadden mentioned. I'm running the tests with lua 5.3.3 though, mainly out of lazyness and because nothing has broken because of that yet ;) 
Do you have any reference to a report regarding the `#` issue? I've not heard of that yet.

**Comment by mpicard** [comment] 2016-10-13 10:29
I'm also using Love2d as the game engine and lua 5.3.3 for busted, I was just wondering if you were testing using luajit, I don't think that's the problem. 

It's not a bug per se but I found [this](http://lua-users.org/lists/lua-l/2012-04/msg00630.html) on the mailing lists with the related [documentation](http://www.lua.org/manual/5.2/manual.html#3.4.6) on the length operator that says the following interesting behaviour...

> Unless a __len metamethod is given, the length of a table t is only defined if the table is a sequence, that is, the set of its positive numeric keys is equal to {1..n} for some non-negative integer n. In that case, n is its length. Note that a table like
> ```lua
> {10, 20, nil, 40}
>```
> is not a sequence, because it has the key 4 but does not have the key 3. (So, there is no n such that the set {1..n} is equal to the set of positive numeric keys of that table.) Note, however, that non-numeric keys do not interfere with whether a table is a sequence. 

```lua
function love.load()
    targets = {}
    targets[1] = "instance of class Entity"
    targets[2] = "instance of class Entity"
    print(#targets)  -- prints 2
    targets[1] = nil
    print(#targets) -- prints 2
    targets[3] = "instance of class Entity"
    print(#targets)  -- prints 3
    targets[3] = nil
    print(#targets) -- prints 2
    targets[4] = "instance of class Entity"
    print(#targets) -- prints 4
end
```
🤔 not intuitive behaviour at all. Thanks for the links @rosshadden I'll have a read!

**Comment by raffomania** [comment] 2016-10-13 12:48
Interesting. I recon we should stop using the `#` operator to find new entity IDs. I must have misread its exact semantics.

**Comment by Nukesor** [comment] 2017-03-12 19:43
I'll close this.
Your "Bug" is wanted behaviour. Our ECS doesn't use entity ids for every component, it uses entity ids for internal management of entities in the engine. Every Entity gets a unique id  and that's it.
You shouldn't encounter any bugs with this, as you shouldn't use the entity id for anything anyway.

**Closed by Nukesor** 2017-03-12 19:43 UTC

**Comment by mpicard** [comment] 2017-03-12 21:53
Oh that's good to know! so use some other identifying component to do
comparisons and then what about the length operator? What would be the best
method to quickly work out the length of entities with a particular
component? It's been a while since I worked on my lua game

**Comment by Nukesor** [comment] 2017-03-13 12:27
The Engine has a function `Engine:getEntitiesWithComponent(component)`. This gives a list with all entities which have the named component. 

```
Engine:getEntitiesWithComponent(component)

component (String) - Class name of the component
Returns a list with all entities that contain this particular component.
```

**Comment by raffomania** [comment] 2017-03-22 11:52
So, after a lot of confusion, to clear this up:

`system.targets` is *not a list*, and thus the `#` doesn't work as expected. We're using global entity ids to index entities in `system.targets`, making it a hashmap/dict. In general, this is not a "wrong" way to store ECS data. It is arguably more cache-friendly to iterate over lists, while hashmaps provide more convenient deletion and fast access via entity ids. Also see [here](https://github.com/amethyst/amethyst/wiki/ECS-Design-Crossroads#components-storage).

We're currently thinking about implementing a `__len` metamethod to count the entries in `system.targets`, either on-the-fly or using a counter keeping track of modifications to the table.
